services:
  - type: web
    name: mmas-system
    env: php
    region: singapore
    plan: free
    buildCommand: cp .env.example .env && composer install --no-dev --optimize-autoloader && php artisan key:generate && php artisan storage:link && npm install && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_DEBUG
        value: true
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://mmas-system.onrender.com
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: mmas-db
          property: connectionString
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM_ADDRESS
        sync: false

databases:
  - name: mmas-db
    region: singapore
    plan: free